[tool.poetry]
name = "pattern-recognition-gr7"
version = "0.1.0"
description = ""
authors = ["YG29 <y.gao.29@student.rug.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
